/* AM2050 — Field Ledger Modernism: attendance concern is a visible follow-up condition, never a hidden score. */
import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, PhoneCall, RefreshCw, Search } from "lucide-react";
import { toast } from "sonner";
import { apiClient } from "@/api/client";
import { LedgerColumn, LedgerTable } from "@/components/shared/LedgerTable";
import { StatusBadge } from "@/components/shared/StatusBadge";

type Defaulter = { id: string; child_unique_id: string; first_name: string; last_name: string; guardian_phone: string | null; last_absence: string; absences: number };

export default function Defaulters() {
  const [records, setRecords] = useState<Defaulter[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState("");
  const load = async () => { setLoading(true); const response = await apiClient.request<Defaulter[]>("/defaulters"); if (response.success) setRecords(response.data); else toast.error(response.error); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => records.filter((record) => `${record.first_name} ${record.last_name} ${record.child_unique_id}`.toLowerCase().includes(query.toLowerCase())), [records, query]);
  const captureFollowup = (record: Defaulter) => { const outcome = window.prompt("Outcome: contacted, home_visit, returned, referred, or unreachable.", "contacted"); if (!outcome) return; if (!["contacted", "home_visit", "returned", "referred", "unreachable"].includes(outcome)) { toast.error("Use a documented follow-up outcome."); return; } const notes = window.prompt("Brief accountable follow-up note:", ""); void apiClient.request(`/defaulters/${record.id}/follow-ups`, { method: "POST", body: { outcome, notes: notes || null } }).then((response) => { if (!response.success) toast.error(response.error); else toast.success("Defaulter follow-up outcome recorded and audited."); }); };
  const columns: LedgerColumn<Defaulter & { localId: string }>[] = [
    { key: "child", label: "Child", cell: (row) => <div><p className="font-semibold text-[#234c64]">{row.first_name} {row.last_name}</p><p className="font-mono text-[0.6rem] text-[#718592]">{row.child_unique_id}</p></div> },
    { key: "signal", label: "Attendance Status", cell: (row) => <StatusBadge label={`${row.absences} absences / 14 days`} tone="attention" /> },
    { key: "last", label: "Last absence", cell: (row) => <span className="font-mono text-xs text-[#5f7580]">{row.last_absence}</span> },
    { key: "followup", label: "Follow-up", cell: (row) => <div className="flex flex-wrap gap-1">{row.guardian_phone ? <a href={`tel:${row.guardian_phone}`} onClick={() => toast.message("Opening guardian contact using this device.")} className="action-press inline-flex items-center gap-1.5 rounded-md border border-[#c88b25] bg-[#fbf2df] px-3 py-2 text-xs font-semibold text-[#815813] hover:bg-[#f6e7c7]"><PhoneCall size={15} /> Call guardian</a> : null}<button onClick={() => captureFollowup(row)} className="action-press rounded-md border border-[#b9c9c0] bg-white px-3 py-2 text-xs font-semibold text-[#234c64]">Record outcome</button></div> },
  ];
  return <main className="paper-grain min-h-[calc(100vh-5.15rem)] px-4 pb-10 pt-6 sm:px-6 lg:px-8 lg:pt-8"><section className="mx-auto max-w-[1440px]"><header className="flex flex-col justify-between gap-4 border-b border-[#cfd9d2] pb-5 lg:flex-row lg:items-end"><div><p className="coordinate-label text-[#956417]">Attendance Monitoring</p><h1 className="mt-2 font-display text-2xl font-semibold tracking-[-0.05em] text-[#123148] sm:text-3xl">Defaulter & Retention Follow-up</h1><p className="mt-2 max-w-2xl text-[0.98rem] leading-6 text-[#57707f]">Identifies students with 3 or more recorded absences in the preceding 14 days for rapid guardian outreach and retention support.</p></div><button onClick={() => void load()} className="action-press inline-flex items-center gap-2 self-start rounded-md border border-[#b9c9c0] bg-white px-4 py-2.5 text-sm font-semibold text-[#234c64] hover:border-[#167a4c] lg:self-auto"><RefreshCw size={16} className={loading ? "animate-spin" : ""} /> Refresh</button></header><div className="mt-5 grid border border-[#d8e0da] bg-white sm:grid-cols-[12rem_1fr]"><div className="border-b border-[#d8e0da] border-l-4 border-l-[#c88b25] p-4 sm:border-b-0 sm:border-r"><p className="coordinate-label text-[#956417]">Current alerts</p><p className="mt-1 font-display text-3xl font-semibold text-[#9b6616]">{records.length}</p></div><div className="p-4"><p className="text-sm font-semibold text-[#234c64]"><AlertTriangle className="mr-1.5 inline text-[#c88b25]" size={16} /> Follow-up remains visible</p><p className="mt-1 text-sm leading-5 text-[#57707f]">A call opens the device dialler only; it does not claim that contact was completed. Record any formal intervention through the appropriate programme workflow.</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#718592]" size={17} /><input className="field-input pl-10" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search child name or ID…" /></div><p className="font-mono text-[0.65rem] uppercase tracking-[0.1em] text-[#718592]">Computed from the last 14 days</p></div><section className="mt-4"><LedgerTable rows={filtered.map((row) => ({ ...row, localId: row.id }))} columns={columns} emptyMessage={loading ? "Calculating scoped attendance alerts…" : "No children currently meet the consecutive-absence threshold in your scope."} /></section></section></main>;
}
