<?php
declare(strict_types=1);

namespace AM2050\Services;

use AM2050\Core\Database;
use AM2050\Support\AuditLogger;
use AM2050\Support\Ulids;
use AM2050\Validation\Validator;
use PDO;
use RuntimeException;

final class UserService
{
    private const ROLES=['super_admin','program_admin','lga_supervisor','ward_supervisor','headmaster','mobilizer','almajiri_liaison','teacher','guardian'];
    private const RULES=['name'=>['type'=>'string','max'=>200,'required'=>true],'role'=>['type'=>'string','in'=>self::ROLES,'required'=>true],'phone'=>['type'=>'string','max'=>20,'required'=>true],'email'=>['type'=>'string','max'=>200,'nullable'=>true],'password'=>['type'=>'string','max'=>255,'required'=>true],'assignedScopeType'=>['type'=>'string','in'=>['state','lga','ward','school','class'],'nullable'=>true],'assignedScopeId'=>['type'=>'string','max'=>26,'nullable'=>true],'assignedCommunityIds'=>['type'=>'array','nullable'=>true],'isActive'=>['type'=>'bool','nullable'=>true],'staffNumber'=>['type'=>'string','max'=>64,'nullable'=>true],'dateOfBirth'=>['type'=>'string','max'=>20,'nullable'=>true],'photoData'=>['type'=>'string','max'=>1500000,'nullable'=>true],'highestQualification'=>['type'=>'string','max'=>255,'nullable'=>true],'rankTitle'=>['type'=>'string','max'=>160,'nullable'=>true],'specialization'=>['type'=>'string','max'=>255,'nullable'=>true]];
    public function __construct(
        private readonly Database $database,
        private readonly AuditLogger $audit,
        private readonly ?CloudinaryService $cloudinary = null
    ) {}

    public function list(array $query): array { [$page,$limit,$offset]=Validator::page($query);$search=trim((string)($query['search']??''));$where='';$params=[];if($search!==''){$where=' WHERE name LIKE :nameSearch OR phone LIKE :phoneSearch OR email LIKE :emailSearch OR staff_number LIKE :staffSearch';$value="%{$search}%";$params=['nameSearch'=>$value,'phoneSearch'=>$value,'emailSearch'=>$value,'staffSearch'=>$value];}$pdo=$this->database->pdo();$count=$pdo->prepare('SELECT COUNT(*) FROM users'.$where);$count->execute($params);$total=(int)$count->fetchColumn();$stmt=$pdo->prepare('SELECT id,name,role,phone,email,staff_number,date_of_birth,photo_data,highest_qualification,rank_title,specialization,subjects_taught,assigned_scope_type,assigned_scope_id,is_active,last_login,created_at,updated_at FROM users'.$where.' ORDER BY created_at DESC LIMIT :limit OFFSET :offset');foreach($params as $key=>$value)$stmt->bindValue(':'.$key,$value);$stmt->bindValue(':limit',$limit,PDO::PARAM_INT);$stmt->bindValue(':offset',$offset,PDO::PARAM_INT);$stmt->execute();$users=$stmt->fetchAll();try{$commStmt=$pdo->query('SELECT uca.user_id, c.id, c.name, c.ward_id FROM user_community_assignments uca INNER JOIN communities c ON c.id=uca.community_id ORDER BY c.name');$commMap=[];foreach($commStmt->fetchAll() as $row){$commMap[$row['user_id']][] = ['id'=>$row['id'],'name'=>$row['name'],'ward_id'=>$row['ward_id']];}foreach($users as &$u){$u['assigned_communities']=$commMap[$u['id']]??[];}}catch(\Throwable){foreach($users as &$u){$u['assigned_communities']=[];}}return ['data'=>$users,'page'=>$page,'limit'=>$limit,'total'=>$total]; }

    public function create(array $auth,array $input): array { $data=Validator::allow($input,self::RULES);$data=$this->normaliseBase($data);$this->validateBase($data);$this->validateScope($data['role'],$data['assignedScopeType']??null,$data['assignedScopeId']??null);$profile=$this->teacherProfile($input,$data['role'],true);$pdo=$this->database->pdo();$this->assertNoUserDuplicate($pdo,$data['phone'],$data['email'],$profile['staffNumber']);$id=Ulids::make();try{$this->insertUser($pdo,$id,$data,$profile,password_hash($data['password'],PASSWORD_BCRYPT));if($data['role']==='headmaster')$pdo->prepare('UPDATE schools SET headmaster_user_id=:user WHERE id=:school')->execute(['user'=>$id,'school'=>$data['assignedScopeId']]);if($data['role']==='mobilizer'&&!empty($input['assignedCommunityIds'])){$this->syncUserCommunities($pdo,$id,$data['assignedScopeId']??null,(array)$input['assignedCommunityIds']);}}catch(\PDOException $error){if($error->getCode()==='23000')throw new RuntimeException('A user already exists with that phone number, email, or staff number.');throw $error;}$record=$this->get($id);$this->audit->record($auth['id'],'CREATE','user',$id,null,$record);return $record; }

    public function submitTeacherRequest(array $auth,array $input):array { $name=trim((string)($input['name']??''));$phone=preg_replace('/\s+/','',(string)($input['phone']??''));$email=isset($input['email'])&&$input['email']!==''?strtolower(trim((string)$input['email'])):null;$password=(string)($input['password']??'');if($name===''||!preg_match('/^0\d{10}$/',$phone))throw new RuntimeException('Provide the teacher name and a valid Nigerian 11-digit phone number.');if($email!==null&&!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Provide a valid email address.');if(strlen($password)<14)throw new RuntimeException('Set a temporary password of at least 14 characters.');if(($auth['assigned_scope_type']??null)!=='school'||empty($auth['assigned_scope_id']))throw new RuntimeException('Headmaster requests require an assigned school scope.');$profile=$this->teacherProfile($input,'teacher',true);$pdo=$this->database->pdo();$this->assertNoUserDuplicate($pdo,$phone,$email,$profile['staffNumber']);$pending=$pdo->prepare("SELECT 1 FROM teacher_registration_requests WHERE status='pending' AND (requested_phone=:phone OR (:hasEmail=1 AND requested_email=:email) OR requested_staff_number=:staffNumber) LIMIT 1");$pending->execute(['phone'=>$phone,'hasEmail'=>$email!==null?1:0,'email'=>$email,'staffNumber'=>$profile['staffNumber']]);if($pending->fetch())throw new RuntimeException('This phone number, email, or staff number already has a pending request.');$id=Ulids::make();$pdo->prepare('INSERT INTO teacher_registration_requests(id,requested_name,requested_phone,requested_email,requested_staff_number,requested_date_of_birth,requested_photo_data,requested_highest_qualification,requested_rank_title,requested_specialization,requested_subjects_taught,requested_password_hash,school_id,requested_by) VALUES(:id,:name,:phone,:email,:staffNumber,:dateOfBirth,:photoData,:qualification,:rankTitle,:specialization,:subjects,:passwordHash,:school,:by)')->execute(['id'=>$id,'name'=>$name,'phone'=>$phone,'email'=>$email,'staffNumber'=>$profile['staffNumber'],'dateOfBirth'=>$profile['dateOfBirth'],'photoData'=>$profile['photoData'],'qualification'=>$profile['highestQualification'],'rankTitle'=>$profile['rankTitle'],'specialization'=>$profile['specialization'],'subjects'=>$profile['subjectsJson'],'passwordHash'=>password_hash($password,PASSWORD_BCRYPT),'school'=>$auth['assigned_scope_id'],'by'=>$auth['id']]);$record=$this->teacherRequest($id);$this->audit->record($auth['id'],'SUBMIT','teacher_registration_request',$id,null,$record);return $record; }

    public function teacherRequests():array { return $this->database->pdo()->query("SELECT r.*,s.school_name,u.name AS requested_by_name FROM teacher_registration_requests r INNER JOIN schools s ON s.id=r.school_id INNER JOIN users u ON u.id=r.requested_by ORDER BY FIELD(r.status,'pending','approved','rejected'),r.created_at DESC")->fetchAll(); }

    public function schoolTeachers(array $auth):array { $pdo=$this->database->pdo();$schoolId=null;if($auth['role']==='headmaster'){$schoolId=($auth['assigned_scope_type']??null)==='school'?$auth['assigned_scope_id']:null;if(!$schoolId)throw new RuntimeException('Headmaster account requires an assigned school.');}if($schoolId!==null){$stmt=$pdo->prepare("SELECT u.id,u.name,u.phone,u.email,u.staff_number,u.highest_qualification,u.rank_title,u.specialization,u.subjects_taught,u.is_active,u.assigned_scope_id,s.school_name,COUNT(DISTINCT c.id) AS assigned_classes FROM users u INNER JOIN schools s ON s.id=:school LEFT JOIN school_classes scoped_class ON scoped_class.id=u.assigned_scope_id LEFT JOIN school_classes c ON c.teacher_id=u.id AND c.school_id=s.id AND c.is_active=1 WHERE u.role='teacher' AND u.is_active=1 AND ((u.assigned_scope_type='school' AND u.assigned_scope_id=s.id) OR (u.assigned_scope_type='class' AND scoped_class.school_id=s.id) OR c.id IS NOT NULL) GROUP BY u.id,s.school_name ORDER BY u.name");$stmt->execute(['school'=>$schoolId]);return $stmt->fetchAll();}$stmt=$pdo->query("SELECT u.id,u.name,u.phone,u.email,u.staff_number,u.highest_qualification,u.rank_title,u.specialization,u.subjects_taught,u.is_active,u.assigned_scope_id,COALESCE(s.school_name,scoped_school.school_name,cs.school_name) AS school_name,COUNT(DISTINCT c.id) AS assigned_classes FROM users u LEFT JOIN schools s ON s.id=u.assigned_scope_id LEFT JOIN school_classes scoped_class ON scoped_class.id=u.assigned_scope_id LEFT JOIN schools scoped_school ON scoped_school.id=scoped_class.school_id LEFT JOIN school_classes c ON c.teacher_id=u.id AND c.is_active=1 LEFT JOIN schools cs ON cs.id=c.school_id WHERE u.role='teacher' GROUP BY u.id,COALESCE(s.school_name,scoped_school.school_name,cs.school_name) ORDER BY school_name,u.name");return $stmt->fetchAll(); }

    public function approveTeacherRequest(array $auth,string $id,array $input):array { $password=(string)($input['temporaryPassword']??'');$pdo=$this->database->pdo();$before=$this->teacherRequest($id);if($before['status']!=='pending')throw new RuntimeException('Only pending teacher requests can be approved.');if($password!==''&&strlen($password)<14)throw new RuntimeException('A replacement temporary password must be at least 14 characters.');$passwordHash=$password!==''?password_hash($password,PASSWORD_BCRYPT):(string)$before['requested_password_hash'];if($passwordHash==='')throw new RuntimeException('The requested temporary password is missing.');return $this->database->transaction(function(PDO $pdo)use($auth,$id,$before,$passwordHash){$userId=Ulids::make();$data=['name'=>$before['requested_name'],'phone'=>$before['requested_phone'],'email'=>$before['requested_email'],'role'=>'teacher','assignedScopeType'=>'school','assignedScopeId'=>$before['school_id'],'isActive'=>true];$profile=['staffNumber'=>$before['requested_staff_number'],'dateOfBirth'=>$before['requested_date_of_birth'],'photoData'=>$before['requested_photo_data'],'highestQualification'=>$before['requested_highest_qualification'],'rankTitle'=>$before['requested_rank_title'],'specialization'=>$before['requested_specialization'],'subjectsJson'=>$before['requested_subjects_taught']];$this->insertUser($pdo,$userId,$data,$profile,$passwordHash);$pdo->prepare("UPDATE teacher_registration_requests SET status='approved',reviewed_by=:by,reviewed_at=NOW(),created_user_id=:user WHERE id=:id")->execute(['by'=>$auth['id'],'user'=>$userId,'id'=>$id]);$after=$this->teacherRequest($id);$this->audit->record($auth['id'],'APPROVE','teacher_registration_request',$id,$before,$after);return $after;}); }

    public function get(string $id): array { $stmt=$this->database->pdo()->prepare('SELECT id,name,role,phone,email,staff_number,date_of_birth,photo_data,highest_qualification,rank_title,specialization,subjects_taught,assigned_scope_type,assigned_scope_id,is_active,last_login,created_at,updated_at FROM users WHERE id=:id');$stmt->execute(['id'=>$id]);$record=$stmt->fetch()?:throw new RuntimeException('User not found.');try{$cStmt=$this->database->pdo()->prepare('SELECT c.id, c.name, c.ward_id FROM user_community_assignments uca INNER JOIN communities c ON c.id=uca.community_id WHERE uca.user_id=:id ORDER BY c.name');$cStmt->execute(['id'=>$id]);$record['assigned_communities']=$cStmt->fetchAll();}catch(\Throwable){$record['assigned_communities']=[];}return $record; }

    public function update(array $auth,string $id,array $input):array { $before=$this->get($id);$allowed=['name','role','assignedScopeType','assignedScopeId','isActive','password','staffNumber','dateOfBirth','photoData','highestQualification','rankTitle','specialization','subjectsTaught'];$data=[];foreach($allowed as $key)if(array_key_exists($key,$input))$data[$key]=$input[$key];if($data===[])throw new RuntimeException('No supported user fields were supplied.');$role=$data['role']??$before['role'];$scopeType=$data['assignedScopeType']??$before['assigned_scope_type'];$scopeId=$data['assignedScopeId']??$before['assigned_scope_id'];$this->validateScope($role,$scopeType,$scopeId);$sets=[];$params=['id'=>$id];$map=['name'=>'name','role'=>'role','assignedScopeType'=>'assigned_scope_type','assignedScopeId'=>'assigned_scope_id','staffNumber'=>'staff_number','dateOfBirth'=>'date_of_birth','photoData'=>'photo_data','highestQualification'=>'highest_qualification','rankTitle'=>'rank_title','specialization'=>'specialization'];foreach($map as$key=>$column)if(array_key_exists($key,$data)){$sets[]=$column.'=:'.$key;$params[$key]=in_array($key,['name','staffNumber','highestQualification','rankTitle','specialization'],true)?trim((string)$data[$key]):$data[$key];}if(array_key_exists('subjectsTaught',$data)){if(!is_array($data['subjectsTaught']))throw new RuntimeException('Subjects taught must be a list.');$sets[]='subjects_taught=:subjectsTaught';$params['subjectsTaught']=json_encode(array_values(array_unique(array_filter(array_map(static fn($subject)=>trim((string)$subject),$data['subjectsTaught'])))),JSON_THROW_ON_ERROR);}if(array_key_exists('isActive',$data)){$sets[]='is_active=:isActive';$params['isActive']=(bool)$data['isActive']?1:0;}if(isset($data['password'])){if(strlen((string)$data['password'])<14)throw new RuntimeException('Password must be at least 14 characters.');$sets[]='password_hash=:passwordHash';$params['passwordHash']=password_hash((string)$data['password'],PASSWORD_BCRYPT);}if($sets===[])throw new RuntimeException('No valid user updates were supplied.');$pdo=$this->database->pdo();$pdo->beginTransaction();try{$pdo->prepare('UPDATE users SET '.implode(',',$sets).' WHERE id=:id')->execute($params);if(isset($data['password'])||array_key_exists('isActive',$data)||isset($data['role'])||array_key_exists('assignedScopeType',$data)||array_key_exists('assignedScopeId',$data))$pdo->prepare('DELETE FROM refresh_tokens WHERE user_id=:id')->execute(['id'=>$id]);if(array_key_exists('assignedCommunityIds',$input)&&$role==='mobilizer'){$this->syncUserCommunities($pdo,$id,$scopeId,(array)$input['assignedCommunityIds']);}$pdo->commit();}catch(\Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}$after=$this->get($id);$this->audit->record($auth['id'],'UPDATE','user',$id,$before,$after);return $after; }

    private function normaliseBase(array $data):array { $data['name']=trim($data['name']);$data['phone']=preg_replace('/\s+/','',$data['phone']);$data['email']=isset($data['email'])&&$data['email']!==null?strtolower(trim($data['email'])):null;return $data; }
    private function validateBase(array $data):void { if($data['name']===''||!preg_match('/^0\d{10}$/',$data['phone']))throw new RuntimeException('Provide a valid Nigerian 11-digit phone number.');if($data['email']!==null&&!filter_var($data['email'],FILTER_VALIDATE_EMAIL))throw new RuntimeException('Provide a valid email address.');if(strlen($data['password'])<14)throw new RuntimeException('Password must be at least 14 characters.'); }
    private function teacherProfile(array $input,string $role,bool $required):array {
        if(!in_array($role,['teacher','headmaster'],true))return ['staffNumber'=>null,'dateOfBirth'=>null,'photoData'=>null,'highestQualification'=>null,'rankTitle'=>null,'specialization'=>null,'subjectsJson'=>null];
        $staffNumber=trim((string)($input['staffNumber']??''));$dateOfBirth=trim((string)($input['dateOfBirth']??''));
        $photoData=isset($input['photoData'])&&$input['photoData']!==''?(string)$input['photoData']:null;
        $highestQualification=trim((string)($input['highestQualification']??''));$rankTitle=trim((string)($input['rankTitle']??''));$specialization=trim((string)($input['specialization']??''));
        $subjects=$input['subjectsTaught']??[];if(!is_array($subjects))throw new RuntimeException('Select one or more taught subjects.');
        $subjects=array_values(array_unique(array_filter(array_map(static fn($value)=>trim((string)$value),$subjects),static fn($value)=>$value!=='')));
        if($required&&($staffNumber===''||$dateOfBirth===''||$photoData===null||$highestQualification===''||$rankTitle===''||$specialization===''||$subjects===[]))throw new RuntimeException('Complete the staff photograph, number, date of birth, qualification, rank, specialization, and taught subjects.');
        if($dateOfBirth!==''&&!preg_match('/^\d{4}-\d{2}-\d{2}$/',$dateOfBirth))throw new RuntimeException('Provide a valid date of birth.');
        if($photoData!==null){
            $isDataUri=str_starts_with($photoData,'data:image/');
            $isHttp=str_starts_with($photoData,'http://')||str_starts_with($photoData,'https://');
            if((!$isDataUri&&!$isHttp)||strlen($photoData)>1500000)throw new RuntimeException('Use a valid staff photograph smaller than 1 MB.');
            if($this->cloudinary!==null&&$this->cloudinary->isConfigured()){
                $uploaded=$this->cloudinary->uploadImage($photoData,'am2050/staff',$staffNumber?:null);
                if($uploaded!==null)$photoData=$uploaded;
            }
        }
        return ['staffNumber'=>$staffNumber?:null,'dateOfBirth'=>$dateOfBirth?:null,'photoData'=>$photoData,'highestQualification'=>$highestQualification?:null,'rankTitle'=>$rankTitle?:null,'specialization'=>$specialization?:null,'subjectsJson'=>$subjects===[]?null:json_encode($subjects,JSON_THROW_ON_ERROR)];
    }
    private function assertNoUserDuplicate(PDO $pdo,string $phone,?string $email,?string $staffNumber):void { $duplicate=$pdo->prepare('SELECT 1 FROM users WHERE phone=:phone OR (:hasEmail=1 AND email=:email) OR (:hasStaff=1 AND staff_number=:staffNumber) LIMIT 1');$duplicate->execute(['phone'=>$phone,'hasEmail'=>$email!==null?1:0,'email'=>$email,'hasStaff'=>$staffNumber!==null?1:0,'staffNumber'=>$staffNumber]);if($duplicate->fetch())throw new RuntimeException('A user already exists with that phone number, email, or staff number.'); }
    private function insertUser(PDO $pdo,string $id,array $data,array $profile,string $passwordHash):void { $pdo->prepare('INSERT INTO users(id,name,role,phone,email,staff_number,date_of_birth,photo_data,highest_qualification,rank_title,specialization,subjects_taught,password_hash,assigned_scope_type,assigned_scope_id,is_active) VALUES(:id,:name,:role,:phone,:email,:staffNumber,:dateOfBirth,:photoData,:qualification,:rankTitle,:specialization,:subjects,:passwordHash,:scopeType,:scopeId,:isActive)')->execute(['id'=>$id,'name'=>$data['name'],'role'=>$data['role'],'phone'=>$data['phone'],'email'=>$data['email'],'staffNumber'=>$profile['staffNumber'],'dateOfBirth'=>$profile['dateOfBirth'],'photoData'=>$profile['photoData'],'qualification'=>$profile['highestQualification'],'rankTitle'=>$profile['rankTitle'],'specialization'=>$profile['specialization'],'subjects'=>$profile['subjectsJson'],'passwordHash'=>$passwordHash,'scopeType'=>$data['assignedScopeType']??null,'scopeId'=>$data['assignedScopeId']??null,'isActive'=>$data['isActive']??true?1:0]); }
    private function teacherRequest(string $id):array { $stmt=$this->database->pdo()->prepare('SELECT * FROM teacher_registration_requests WHERE id=:id');$stmt->execute(['id'=>$id]);return $stmt->fetch()?:throw new RuntimeException('Teacher registration request not found.'); }
    private function validateScope(string $role,?string $type,?string $id):void { if($role==='super_admin'){if($type!==null||$id!==null)throw new RuntimeException('Super administrators must not have a geographic scope.');return;}if($type===null||$id===null||!preg_match('/^[0-9A-HJKMNP-TV-Z]{26}$/',$id))throw new RuntimeException('A valid assigned scope is required for this role.');$tables=['state'=>'states','lga'=>'lgas','ward'=>'wards','school'=>'schools','class'=>'school_classes'];$table=$tables[$type]??null;if($table===null)throw new RuntimeException('Invalid scope type.');$check=$this->database->pdo()->prepare('SELECT id FROM '.$table.' WHERE id=:id LIMIT 1');$check->execute(['id'=>$id]);if(!$check->fetch())throw new RuntimeException('Assigned scope does not exist.'); }
    private function syncUserCommunities(PDO $pdo, string $userId, ?string $wardId, array $communityIds): void {
        $communityIds = array_values(array_unique(array_filter(array_map('strval', $communityIds))));
        if (count($communityIds) > 5) throw new RuntimeException('A mobilizer can be assigned to a maximum of 5 communities.');
        if (count($communityIds) < 1) throw new RuntimeException('A mobilizer must be assigned to between 1 and 5 communities.');
        if ($wardId) {
            $stmt = $pdo->prepare('SELECT id FROM communities WHERE id = :id AND ward_id = :ward');
            foreach ($communityIds as $cid) {
                $stmt->execute(['id' => $cid, 'ward' => $wardId]);
                if (!$stmt->fetch()) throw new RuntimeException("Community {$cid} does not exist or does not belong to the assigned ward.");
            }
        }
        $pdo->prepare('DELETE FROM user_community_assignments WHERE user_id = :user')->execute(['user' => $userId]);
        $ins = $pdo->prepare('INSERT INTO user_community_assignments (id, user_id, community_id, created_at) VALUES (:id, :user, :comm, NOW())');
        foreach ($communityIds as $cid) {
            $ins->execute(['id' => Ulids::make(), 'user' => $userId, 'comm' => $cid]);
        }
    }
}
